name: 'Install Terraform'
description: 'Installs any version of terraform to the current job environment'
branding:
  icon: type
  color: purple
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  creds:
    description: 'YAML Array of credential objects (`machine`, `login`, `password`)'
    required: true
outputs: # none
