name: 'Netrc Credentials'
description: 'Sets up netrc credentials'
branding:
  icon: lock
  color: yellow
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  creds:
    description: 'YAML Array of credential objects (`machine`, `login`, `password`)'
    required: true
outputs: # none
