name: Tests

on: [push]

env:
  login: l12s-bot

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm test
    - name: Apply netrc creds
      uses: little-core-labs/netrc-creds@master
      with:
        creds: |
          [
            {
              "machine": "github.com",
              "login": "${{env.login}}",
              "password": "1234"
            },
            {
              "machine": "api.github.com",
              "login": "${{env.login}}",
              "password": "1234"
            }
          ]
    - name: Look at results
      run: |
        cat ~/.netrc

